name: bench
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ master ]
jobs: 
  nhttp:
    runs-on: ubuntu-latest
    outputs: 
      result_path: '${{ steps.result.outputs.result_path }}'
      result: '${{ steps.result.outputs.result }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts nhttp
      - name: End Bench
        id: result
        run: | 
          RESULT_PATH="frameworks/nhttp/result.json"
          RESULT="$(cat frameworks/nhttp/result.json)"
          echo "::set-output name=result_path::$RESULT_PATH"
          echo "::set-output name=result::$RESULT"
  oak:
    runs-on: ubuntu-latest
    outputs: 
      result_path: '${{ steps.result.outputs.result_path }}'
      result: '${{ steps.result.outputs.result }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts oak
      - name: End Bench
        id: result
        run: | 
          RESULT_PATH="frameworks/oak/result.json"
          RESULT="$(cat frameworks/oak/result.json)"
          echo "::set-output name=result_path::$RESULT_PATH"
          echo "::set-output name=result::$RESULT"
  results: 
    runs-on: ubuntu-latest
    needs:
      - nhttp
      - oak
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Result nhttp
        run: > 
          echo '${{needs.nhttp.outputs.result}}' | jq . | tee
          ${{needs.nhttp.outputs.result_path}}
      - name: Result oak
        run: > 
          echo '${{needs.oak.outputs.result}}' | jq . | tee
          ${{needs.oak.outputs.result_path}}
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Readme
        run: deno run -A ./helpers/readme.ts
      - name: Commit
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: bot@example.com
          coauthor_name: bot_ci
          branch: master
      
