name: bench
on:
  push:
    branches: [ master ]
jobs: 
  nhttp:
    runs-on: ubuntu-latest
    output: 
      result: '${{ steps.result.output.result }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts nhttp
      - name: End Bench
        id: result
        run: | 
          RESULT="frameworks/nhttp/result.json"
          echo "::set-output name=result::$RESULT"

  oak:
    runs-on: ubuntu-latest
    output: 
      result: '${{ steps.result.output.result }}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts oak
      - name: End Bench
        id: result
        run: | 
          RESULT="frameworks/oak/result.json"
          echo "::set-output name=result::$RESULT"
  results: 
    runs-on: ubuntu-latest
    inc:
      - nhttp
      - oak
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Result nhttp
        run: echo '${{inc.nhttp.output.result}}'
      - name: Result oak
        run: echo '${{inc.oak.output.result}}'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Readme
        run: deno run -A readme.ts
      - name: Commit
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: bot@example.com
          coauthor_name: bot_ci
          branch: master
      
