name: bench
on:
  push:
    branches: [ master ]
jobs: 
  nhttp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts nhttp
      - name: End Bench
        run: echo "End Bench"
  oak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Install Autocannon
        run: npm install autocannon -g
      - name: Start Bench
        run: deno run -A bench.ts oak
      - name: End Bench
        run: echo "End Bench"
  results: 
    runs-on: ubuntu-latest
    needs:
      - nhttp
      - oak
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup deno latest
        uses: denoland/setup-deno@main
      - name: Readme
        run: deno run -A readme.ts
      - name: Commit
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          coauthor_email: bot@example.com
          coauthor_name: bot_ci
          branch: master
      
